/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};

/// struct for typed errors of method [`tax_preview_amount_organization_trial_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TaxPreviewAmountOrganizationTrialPostError {
    UnknownValue(serde_json::Value),
}

pub async fn tax_preview_amount_organization_trial_post(
    configuration: &configuration::Configuration,
    preview_tax_amount_for_organization_trial_request_body: Option<
        models::PreviewTaxAmountForOrganizationTrialRequestBody,
    >,
) -> Result<(), Error<TaxPreviewAmountOrganizationTrialPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_preview_tax_amount_for_organization_trial_request_body =
        preview_tax_amount_for_organization_trial_request_body;

    let uri_str = format!(
        "{}/tax/preview-amount/organization-trial",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_preview_tax_amount_for_organization_trial_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<TaxPreviewAmountOrganizationTrialPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
