/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use crate::models;
///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum GatewayType {
    Stripe = 0,
    Braintree = 1,
    AppStore = 2,
    PlayStore = 3,
    BitPay = 4,
    PayPal = 5,
    Bank = 6,
}

impl std::fmt::Display for GatewayType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Stripe => "0",
                Self::Braintree => "1",
                Self::AppStore => "2",
                Self::PlayStore => "3",
                Self::BitPay => "4",
                Self::PayPal => "5",
                Self::Bank => "6",
            }
        )
    }
}
impl Default for GatewayType {
    fn default() -> GatewayType {
        Self::Stripe
    }
}
