/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use crate::models;
///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum IntegrationType {
    CloudBillingSync = 1,
    Scim = 2,
    Slack = 3,
    Webhook = 4,
    Hec = 5,
}

impl std::fmt::Display for IntegrationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::CloudBillingSync => "1",
                Self::Scim => "2",
                Self::Slack => "3",
                Self::Webhook => "4",
                Self::Hec => "5",
            }
        )
    }
}
impl Default for IntegrationType {
    fn default() -> IntegrationType {
        Self::CloudBillingSync
    }
}
