/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MasterPasswordUnlockResponseModel {
    #[serde(rename = "kdf")]
    pub kdf: Box<models::MasterPasswordUnlockKdfResponseModel>,
    #[serde(rename = "masterKeyEncryptedUserKey")]
    pub master_key_encrypted_user_key: Option<String>,
    #[serde(rename = "salt")]
    pub salt: Option<String>,
}

impl MasterPasswordUnlockResponseModel {
    pub fn new(
        kdf: models::MasterPasswordUnlockKdfResponseModel,
        master_key_encrypted_user_key: Option<String>,
        salt: Option<String>,
    ) -> MasterPasswordUnlockResponseModel {
        MasterPasswordUnlockResponseModel {
            kdf: Box::new(kdf),
            master_key_encrypted_user_key,
            salt,
        }
    }
}
