/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MasterPasswordUnlockDataModel {
    #[serde(rename = "kdfType")]
    pub kdf_type: models::KdfType,
    #[serde(rename = "kdfIterations")]
    pub kdf_iterations: i32,
    #[serde(rename = "kdfMemory", skip_serializing_if = "Option::is_none")]
    pub kdf_memory: Option<i32>,
    #[serde(rename = "kdfParallelism", skip_serializing_if = "Option::is_none")]
    pub kdf_parallelism: Option<i32>,
    #[serde(rename = "email")]
    pub email: Option<String>,
    #[serde(rename = "masterKeyAuthenticationHash")]
    pub master_key_authentication_hash: Option<String>,
    #[serde(rename = "masterKeyEncryptedUserKey")]
    pub master_key_encrypted_user_key: Option<String>,
    #[serde(rename = "masterPasswordHint", skip_serializing_if = "Option::is_none")]
    pub master_password_hint: Option<String>,
}

impl MasterPasswordUnlockDataModel {
    pub fn new(
        kdf_type: models::KdfType,
        kdf_iterations: i32,
        email: Option<String>,
        master_key_authentication_hash: Option<String>,
        master_key_encrypted_user_key: Option<String>,
    ) -> MasterPasswordUnlockDataModel {
        MasterPasswordUnlockDataModel {
            kdf_type,
            kdf_iterations,
            kdf_memory: None,
            kdf_parallelism: None,
            email,
            master_key_authentication_hash,
            master_key_encrypted_user_key,
            master_password_hint: None,
        }
    }
}
