/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use crate::models;
///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum OrganizationApiKeyType {
    Default = 0,
    BillingSync = 1,
    Scim = 2,
}

impl std::fmt::Display for OrganizationApiKeyType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Default => "0",
                Self::BillingSync => "1",
                Self::Scim => "2",
            }
        )
    }
}
impl Default for OrganizationApiKeyType {
    fn default() -> OrganizationApiKeyType {
        Self::Default
    }
}
