/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationPasswordManagerRequestModel {
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<models::PlanType>,
    #[serde(rename = "sponsoredPlan", skip_serializing_if = "Option::is_none")]
    pub sponsored_plan: Option<models::PlanSponsorshipType>,
    #[serde(rename = "seats", skip_serializing_if = "Option::is_none")]
    pub seats: Option<i32>,
    #[serde(rename = "additionalStorage", skip_serializing_if = "Option::is_none")]
    pub additional_storage: Option<i32>,
}

impl OrganizationPasswordManagerRequestModel {
    pub fn new() -> OrganizationPasswordManagerRequestModel {
        OrganizationPasswordManagerRequestModel {
            plan: None,
            sponsored_plan: None,
            seats: None,
            additional_storage: None,
        }
    }
}
