/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use crate::models;
///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum ProductTierType {
    Free = 0,
    Families = 1,
    Teams = 2,
    Enterprise = 3,
    TeamsStarter = 4,
}

impl std::fmt::Display for ProductTierType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Free => "0",
                Self::Families => "1",
                Self::Teams => "2",
                Self::Enterprise => "3",
                Self::TeamsStarter => "4",
            }
        )
    }
}
impl Default for ProductTierType {
    fn default() -> ProductTierType {
        Self::Free
    }
}
