/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use crate::models;
///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum PushType {
    SyncCipherUpdate = 0,
    SyncCipherCreate = 1,
    SyncLoginDelete = 2,
    SyncFolderDelete = 3,
    SyncCiphers = 4,
    SyncVault = 5,
    SyncOrgKeys = 6,
    SyncFolderCreate = 7,
    SyncFolderUpdate = 8,
    SyncCipherDelete = 9,
    SyncSettings = 10,
    LogOut = 11,
    SyncSendCreate = 12,
    SyncSendUpdate = 13,
    SyncSendDelete = 14,
    AuthRequest = 15,
    AuthRequestResponse = 16,
    SyncOrganizations = 17,
    SyncOrganizationStatusChanged = 18,
    SyncOrganizationCollectionSettingChanged = 19,
    Notification = 20,
    NotificationStatus = 21,
    RefreshSecurityTasks = 22,
}

impl std::fmt::Display for PushType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::SyncCipherUpdate => "0",
                Self::SyncCipherCreate => "1",
                Self::SyncLoginDelete => "2",
                Self::SyncFolderDelete => "3",
                Self::SyncCiphers => "4",
                Self::SyncVault => "5",
                Self::SyncOrgKeys => "6",
                Self::SyncFolderCreate => "7",
                Self::SyncFolderUpdate => "8",
                Self::SyncCipherDelete => "9",
                Self::SyncSettings => "10",
                Self::LogOut => "11",
                Self::SyncSendCreate => "12",
                Self::SyncSendUpdate => "13",
                Self::SyncSendDelete => "14",
                Self::AuthRequest => "15",
                Self::AuthRequestResponse => "16",
                Self::SyncOrganizations => "17",
                Self::SyncOrganizationStatusChanged => "18",
                Self::SyncOrganizationCollectionSettingChanged => "19",
                Self::Notification => "20",
                Self::NotificationStatus => "21",
                Self::RefreshSecurityTasks => "22",
            }
        )
    }
}
impl Default for PushType {
    fn default() -> PushType {
        Self::SyncCipherUpdate
    }
}
