/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetupBusinessUnitRequestBody {
    #[serde(rename = "userId")]
    pub user_id: uuid::Uuid,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "providerKey")]
    pub provider_key: String,
    #[serde(rename = "organizationKey")]
    pub organization_key: String,
}

impl SetupBusinessUnitRequestBody {
    pub fn new(
        user_id: uuid::Uuid,
        token: String,
        provider_key: String,
        organization_key: String,
    ) -> SetupBusinessUnitRequestBody {
        SetupBusinessUnitRequestBody {
            user_id,
            token,
            provider_key,
            organization_key,
        }
    }
}
