/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnlockDataRequestModel {
    #[serde(rename = "masterPasswordUnlockData")]
    pub master_password_unlock_data: Box<models::MasterPasswordUnlockDataModel>,
    #[serde(rename = "emergencyAccessUnlockData")]
    pub emergency_access_unlock_data: Option<Vec<models::EmergencyAccessWithIdRequestModel>>,
    #[serde(rename = "organizationAccountRecoveryUnlockData")]
    pub organization_account_recovery_unlock_data:
        Option<Vec<models::ResetPasswordWithOrgIdRequestModel>>,
    #[serde(rename = "passkeyUnlockData")]
    pub passkey_unlock_data: Option<Vec<models::WebAuthnLoginRotateKeyRequestModel>>,
    #[serde(rename = "deviceKeyUnlockData")]
    pub device_key_unlock_data: Option<Vec<models::OtherDeviceKeysUpdateRequestModel>>,
}

impl UnlockDataRequestModel {
    pub fn new(
        master_password_unlock_data: models::MasterPasswordUnlockDataModel,
        emergency_access_unlock_data: Option<Vec<models::EmergencyAccessWithIdRequestModel>>,
        organization_account_recovery_unlock_data: Option<
            Vec<models::ResetPasswordWithOrgIdRequestModel>,
        >,
        passkey_unlock_data: Option<Vec<models::WebAuthnLoginRotateKeyRequestModel>>,
        device_key_unlock_data: Option<Vec<models::OtherDeviceKeysUpdateRequestModel>>,
    ) -> UnlockDataRequestModel {
        UnlockDataRequestModel {
            master_password_unlock_data: Box::new(master_password_unlock_data),
            emergency_access_unlock_data,
            organization_account_recovery_unlock_data,
            passkey_unlock_data,
            device_key_unlock_data,
        }
    }
}
