/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UntrustDevicesRequestModel {
    #[serde(rename = "devices")]
    pub devices: Vec<uuid::Uuid>,
}

impl UntrustDevicesRequestModel {
    pub fn new(devices: Vec<uuid::Uuid>) -> UntrustDevicesRequestModel {
        UntrustDevicesRequestModel { devices }
    }
}
